[tool.poetry]
name = "orm"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
peewee = "3.17.8"
psycopg2-binary = "2.9.10"
python = "3.13.1"

[tool.poetry.group.dev.dependencies]
types-peewee = "3.17.6.20240806"
